---
- hosts: webservers 
  become: True
  tasks:
    - name: update the repo
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true  
    - name: Install packages
      apt:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
